<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>OnlineVideos.Sites</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>

  <PropertyGroup>
    <Title>OnlineVideos.Sites.offbyone</Title>
    <Product>OnlineVideos</Product>
    <Description>SiteUtils for OnlineVideos by offbyone</Description>
  </PropertyGroup>
    
  <ItemGroup>
    <Reference Include="System.Net" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Net.Http.WebRequest" />
    <Reference Include="System.Web" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\..\OnlineVideos\OnlineVideos.csproj" />
  </ItemGroup>
  <UsingTask TaskName="ILMerge.MSBuild.Tasks.ILMerge" AssemblyFile="$(PkgILMerge_MSBuild_Tasks)\tools\ILMerge.MSBuild.Tasks.dll" />
  <ItemGroup>
    <MergeAsm Include="$(TargetPath)" />
    <MergeAsm Include="$(TargetDir)Google.Apis.Auth.dll" />
    <MergeAsm Include="$(TargetDir)Google.Apis.Core.dll" />
    <MergeAsm Include="$(TargetDir)Google.Apis.dll" />
    <MergeAsm Include="$(TargetDir)Google.Apis.YouTube.v3.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Apis" Version="1.70.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.70.0" />
    <PackageReference Include="Google.Apis.Core" Version="1.70.0" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.70.0.3847" />
    <PackageReference Include="ILMerge.MSBuild.Tasks" Version="1.0.0.3" />
  </ItemGroup>
  <Target Name="AfterClean">
    <Delete Files="..\..\Build\SiteUtilDlls\$(TargetFileName)" />
    <Delete Files="..\..\Build\SiteUtilDlls\$(TargetName).pdb" />
  </Target>
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
    <ItemGroup>
      <ExternalPdbs Include="$(TargetDir)Google*.pdb" />
    </ItemGroup>
    <Delete Files="@(ExternalPdbs)" ContinueOnError="true" />
    <ILMerge InputAssemblies="@(MergeAsm)" LibraryPath="..\..\OnlineVideos\bin\$(Configuration)" DebugInfo="true" OutputFile="..\..\Build\SiteUtilDlls\$(TargetFileName)" />
  </Target>
  <Target Name="EnsureBclBuildImported" BeforeTargets="BeforeBuild" Condition="'$(BclBuildImported)' == ''" />
</Project>