<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>OnlineVideos.Sites</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputPath>..\..\Build\SiteUtilDlls\</OutputPath>
    <DebugType Condition="'$(Configuration)' != 'Release'">full</DebugType>
  </PropertyGroup>

  <PropertyGroup>
    <Title>OnlineVideos.Sites.offbyone</Title>
    <Product>OnlineVideos</Product>
    <Description>SiteUtils for OnlineVideos by offbyone</Description>
  </PropertyGroup>
    
  <ItemGroup>
    <Reference Include="System.Net" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Net.Http.WebRequest" />
    <Reference Include="System.Web" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\..\OnlineVideos\OnlineVideos.csproj" />
  </ItemGroup>
  <UsingTask TaskName="ILMerge.MSBuild.Tasks.ILMerge" AssemblyFile="$(PkgILMerge_MSBuild_Tasks)\tools\ILMerge.MSBuild.Tasks.dll" />
  <ItemGroup>
    <MergeAsm Include="$(IntermediateOutputPath)$(TargetFileName)" />
    <MergeAsm Include="$(TargetDir)Google.Apis.Auth.dll" />
    <MergeAsm Include="$(TargetDir)Google.Apis.Core.dll" />
    <MergeAsm Include="$(TargetDir)Google.Apis.dll" />
    <MergeAsm Include="$(TargetDir)Google.Apis.YouTube.v3.dll" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Apis" Version="1.70.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.70.0" />
    <PackageReference Include="Google.Apis.Core" Version="1.70.0" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.70.0.3847" />
    <PackageReference Include="ILMerge.MSBuild.Tasks" Version="1.0.0.3" />
  </ItemGroup>

  <Target Name="CustomAfterBuild" AfterTargets="Build">
    <ItemGroup>
      <ExternalPdbs Include="$(TargetDir)Google*.pdb" />
    </ItemGroup>
    <Delete Files="@(ExternalPdbs)" ContinueOnError="true" />
    <ILMerge 
        InputAssemblies="@(MergeAsm)"
        LibraryPath="$(TargetDir)"
        DebugInfo="$('$(Configuration)' != 'Release')"
        Internalize="true"
        OutputFile="$(TargetPath)" />
  </Target>
</Project>