<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))" Condition="'' != $([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))" />
    
  <PropertyGroup>
    <PluginDestination>$(MediaPortalInstallPath)\plugins\Windows\</PluginDestination>
    <DataDestination>$(ProgramData)$(_MediaPortalSubPath)\</DataDestination>
  </PropertyGroup>

  <ItemGroup>
    <PluginFiles Include="$(TargetDir)$(TargetName).*" />
    <APIFiles Include="$(TargetDir)OnlineVideos.dll" />
    <APIFiles Include="$(TargetDir)OnlineVideos.pdb" Condition=" '$(Configuration)' == 'Debug' "/>
    <SiteUtilDllFiles Include="$(RepoRoot)Build\SiteUtilDlls\OnlineVideos.Sites.*.dll" />
    <SiteUtilDllFiles Include="$(RepoRoot)Build\SiteUtilDlls\OnlineVideos.Sites.*.pdb" Condition=" '$(Configuration)' == 'Debug' "/>
    <IconFiles Include="$(RepoRoot)SiteImages\**\*.*" />
    <LanguageFiles Include="$(RepoRoot)Language\OnlineVideos\*.xml" />
    <SkinFiles Include="$(RepoRoot)Skins\**\*.*" />
  </ItemGroup>

  <Target Name="CustomAfterBuild" AfterTargets="Build">
    <Error Condition="'$(MediaPortalInstallPath)' == ''" Text="MediaPortalInstallPath is not set." />
  </Target>

  <Target Name="CustomAfterBuild" AfterTargets="Build" Condition="'$(CopyBuildResultToMediaPortalInstallPath)' == 'True'">
    <Copy SourceFiles="@(PluginFiles)" DestinationFolder="$(PluginDestination)" />
    <Copy SourceFiles="@(APIFiles)" DestinationFolder="$(PluginDestination)OnlineVideos\" />
    <Copy SourceFiles="@(SiteUtilDllFiles)" DestinationFolder="$(PluginDestination)OnlineVideos\" />
    <Copy SourceFiles="@(LanguageFiles)" DestinationFolder="$(DataDestination)language\OnlineVideos\" />
    <Copy SourceFiles="@(SkinFiles)"
          DestinationFiles="@(SkinFiles->'$(DataDestination)Skin\%(RecursiveDir)%(Filename)%(Extension)')" />
    <Copy SourceFiles="@(IconFiles)"
          DestinationFiles="@(IconFiles->'$(DataDestination)thumbs\OnlineVideos\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
</Project>
