<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <NoWarn>MSB3270</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <Title>OnlineVideos MediaPortal1 GUI</Title>
    <Product>OnlineVideos</Product>
    <Description>OnlineVideos GUI FrontEnd for MediaPortal 1</Description>
  </PropertyGroup>
    
  <ItemGroup>
    <Reference Include="AxInterop.WMPLib">
      <HintPath>$(MediaPortalInstallPath)\AxInterop.WMPLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Common.GUIPlugins">
      <HintPath>$(MediaPortalInstallPath)\plugins\Windows\Common.GUIPlugins.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Common.Utils">
      <HintPath>$(MediaPortalInstallPath)\Common.Utils.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Core">
      <HintPath>$(MediaPortalInstallPath)\Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Databases">
      <HintPath>$(MediaPortalInstallPath)\Databases.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Dialogs">
      <HintPath>$(MediaPortalInstallPath)\plugins\Windows\Dialogs.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="DirectShowLib">
      <HintPath>$(MediaPortalInstallPath)\DirectShowLib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="GUIHome">
      <HintPath>$(MediaPortalInstallPath)\plugins\Windows\GUIHome.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="GUIVideos">
      <HintPath>$(MediaPortalInstallPath)\plugins\Windows\GUIVideos.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Interop.WMPLib">
      <HintPath>$(MediaPortalInstallPath)\Interop.WMPLib.dll</HintPath>
      <EmbedInteropTypes>False</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
    <Reference Include="log4net">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(MediaPortalInstallPath)\log4net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MediaInfo.Wrapper">
      <HintPath>$(MediaPortalInstallPath)\MediaInfo.Wrapper.dll</HintPath>
    </Reference>
    <Reference Include="RemotePlugins">
      <HintPath>$(MediaPortalInstallPath)\RemotePlugins.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Design" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Services" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="TraktAPI">
      <HintPath>Trakt\TraktAPI.dll</HintPath>
    </Reference>
    <Reference Include="TraktPlugin, Version=5.6.0.0, Culture=neutral, processorArchitecture=x86">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>Trakt\TraktPlugin.dll</HintPath>
    </Reference>
    <Reference Include="Utils">
      <HintPath>$(MediaPortalInstallPath)\Utils.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Configuration\ObjectListView\DataListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\FastDataListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\FastObjectListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\Implementation\Enums.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\Implementation\Events.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\ObjectListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\OLVColumn.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\Rendering\Renderers.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\Rendering\Styles.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\Rendering\TreeRenderer.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\SubControls\ToolStripCheckedListBox.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\TreeListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\ObjectListView\VirtualObjectListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Configuration\PreferredListControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Configuration\TablessTabControl .cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Initialization.cs">
      <DependentUpon>GUIOnlineVideos.cs</DependentUpon>
    </Compile>
    <Compile Update="Player\Vlc.DotNet\Vlc.DotNet.Core\VlcEventHandler%27.cs" />
    <Compile Update="Player\Vlc.DotNet\Vlc.DotNet.Forms\VlcControl.Common.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Player\Vlc.DotNet\Vlc.DotNet.Forms\VlcControl.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="OnlineVideos.png" />
    <EmbeddedResource Include="OnlineVideosDisabled.png" />
    <EmbeddedResource Include="Resources\*.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OnlineVideos\OnlineVideos.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Directory.Build.targets">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
    
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2277.86" />
  </ItemGroup>
</Project>
