<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\Debug</OutputPath>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <OutputPath>bin\Release</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <StartAction>Program</StartAction>
    <StartProgram>$(MediaPortalInstallPath)\mediaportal.exe</StartProgram>
    <RemoteDebugEnabled>false</RemoteDebugEnabled>
    <StartWorkingDirectory>$(MediaPortalInstallPath)</StartWorkingDirectory>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Runtime.Caching" />
    <Reference Include="System.Security" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Services" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="WebService\CompressionWebClient.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="3rdParty\RssToolkit\Resources\Rss20.xsd" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="3rdParty\RssToolkit\Resources\AtomToRss20.xsl" />
    <EmbeddedResource Include="3rdParty\RssToolkit\Resources\RdfToRss20.xsl" />
    <EmbeddedResource Include="3rdParty\RssToolkit\Resources\Rss20ToAtom.xsl" />
    <EmbeddedResource Include="3rdParty\RssToolkit\Resources\Rss20ToOpml.xsl" />
    <EmbeddedResource Include="3rdParty\RssToolkit\Resources\Rss20ToRdf.xsl" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="OnlineVideoSites.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Down.png" />
    <Content Include="Resources\Up.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.46" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2277.86" />
    <PackageReference Include="MSBuildTasks" Version="1.5.0.235" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
    <PackageReference Include="SubtitleDownloader" Version="3.1.4">
      <Aliases>OVSubs</Aliases>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Label="Compile items now included by globbing that were not in the original project file">
    <Compile Remove="MPUrlSourceFilter\MPUrlSourceSplitterError.cs" />
  </ItemGroup>
  <Target Name="AfterBuild">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)NuGetPackage\Content\" />
  </Target>
</Project>
