<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>OnlineVideos.Sites</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputPath>..\..\Build\SiteUtilDlls\</OutputPath>      
  </PropertyGroup>

  <PropertyGroup>
    <Title>OnlineVideos.Sites.doskabouter</Title>
    <Description>SiteUtils for OnlineVideos by doskabouter</Description>
    <Product>OnlineVideos.Sites.doskabouter</Product>
    <Copyright>Copyright ©  2010</Copyright>
  </PropertyGroup>
    
  <ItemGroup>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\OnlineVideos\bin\$(Configuration)\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Web" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\..\OnlineVideos\OnlineVideos.csproj" />
  </ItemGroup>
  <PropertyGroup />
</Project>